### ISSUE TITLE
Add a warning regarding nginx proxy_pass

### ISSUE THREAD

**Issue by Wardormeur** [NodeBB/docs#22]
Hi !
In [the nginx config documentation](https://github.com/NodeBB/docs/blob/97a551969a27c3d1501dfeb8211dd98a625bed2d/docs/configuring/proxies/nginx.md), the proxy_pass redirect to http://127.0.0.1:4567;
By setting a "/" at the end of that url, url are decoded (https://serverfault.com/questions/459369/disabling-url-decoding-in-nginx-proxy#comment610623_463932) and hence vulnerable to XSS (https://github.com/NodeBB/NodeBB/issues/4192).
It's fairly easy to make the mistake of putting an ending slash (and the proxy still work), so that a warning in the doc would be welcome.
Apart from ours instances, I've spotted a couple of websites having the same issue :)

**Comment by julianlam** [comment]
Hello @Wardormeur -- very good to know! I will add the warning today, or if you'd like you can edit the files in GitHub themselves and submit a pull request 😄
