### ISSUE TITLE
Debain docs outdated / Merge with Ubuntu?

### ISSUE THREAD

**Issue by angristan** [NodeBB/docs#31]
The Debian installation page is very outdated, since it mentions Wheezy, Node 0.12, etc.

I was going to update it but the Ubuntu page will basically work exactly the same, besides 2 or 3 repositories that are also available on Debian.

I have 2 propositions:

- To rewrite the Debian page from the Ubuntu page (= paste the Ubuntu page and make a few changes)
- To merge both pages and point out differences. (This might not even be needed if we use `lsb_release` for the repositories URL, for instance).

What do you think? Both should be pretty quick and easy to do.

**Comment by julianlam** [comment]
As always I'd recommend opening a PR if you can 😁

With respect to Debian vs Ubuntu, as long as Debian testing uses Node v8.x you should be good to copy/paste the Ubuntu docs. I have a feeling stable doesn't use v8.x though...

**Comment by angristan** [comment]
Yes, I was planning on doing so but I wanted to know what to do before ^^

Usually, on Debian, Node is not installed from the Debian repo but from nodesource: https://github.com/nodesource/distributions/blob/master/README.md. This is what is currently used by the Ubuntu tutorial, so they can have the exact same version.

**Comment by julianlam** [comment]
Then perfect, as long as you run through the instructions once and they work identically to the Ubuntu version, I see no reason you can just copy one over to the other, or even just merge the two.

**Comment by angristan** [comment]
OK, expect a PR 👍

**Comment by psychobunny** [comment]
looks like you've done the heavy lifting but we forgot to close this
https://github.com/NodeBB/docs/pull/32

thank you!
