### ISSUE TITLE
Mongodb systemd problems

### ISSUE THREAD

**Issue by evaldosantos** [NodeBB/docs#5]
I wanna know from you guys how to improve the docs. I'm following the instructions to run mongodb, when I try to start the mongod service, I get an error: 
vagrant@vagrant-ubuntu-trusty-64:~$ sudo systemctl start mongod                                              
sudo: systemctl: command not found 

I have to install systemd to solve this
$ sudo apt-get install systemd

After do this I was able to run the commands:
$ sudo service mongod start
$ sudo service mongod status

**Comment by evaldosantos** [comment]
What do you think about this?
I know that isn't the purpose of the wiki install the dependencies...

**Comment by julianlam** [comment]
I believe trusty is way too old. Even out of LTS, although I may be mistaken... you should use 16.04, and so there is no need to change the docs as they're optimized for 16.04
