### ISSUE TITLE
Error in document

### ISSUE THREAD

**Issue by shlomo-shlomo** [NodeBB/docs#57]
Here: https://docs.nodebb.org/installing/cloud/heroku/ You can use heroku's free database while it closes - https://devcenter.heroku.com/changelog-items/1823

**Comment by julianlam** [comment]
@shlomo-shlomo Thanks for letting us know. Unfortunately the Heroku documentation is community-maintained, and I am not familiar with alternative MongoDB add-ons for Heroku. If you are, would you mind opening a PR to fix the documentation?

**Comment by shlomo-shlomo** [comment]
@julianlam You can use the free clever-cloud.com program
From experience it works great!
I think I do not know enough English so that I can correct myself.
