### ISSUE TITLE
ubuntu install file is non-existent in github?

### ISSUE THREAD

**Issue by meelash** [NodeBB/docs#63]
I'm trying to edit the broken link to Configuring Databases on the ubuntu install page. But the link to edit the page leads to https://github.com/NodeBB/docs/edit/master/src/docs/installing/os/ubuntu.md which does not exist. Can't find where the source is of the ubuntu docs.

**Comment by pitaj** [comment]
It's generated by templates: https://github.com/NodeBB/docs/tree/master/src/templates/installing/os/ubuntu

**Comment by splumb** [comment]
I guess the [path ](https://raw.githubusercontent.com/NodeBB/docs/master/src/templates/installing/os/template.md)has must be updated.
`For more information, go to the [configuring nginx](../configuring/nginx) page.`
but it should be "../configuring/proxies/nginx"
