### ISSUE TITLE
requirejs Removed

### ISSUE THREAD

**Issue by ShlomoCode** [NodeBB/docs#66]
in https://docs.nodebb.org/development/plugins/libraries/
(https://github.com/NodeBB/docs/blob/master/src/docs/development/plugins/libraries.md):

>From your client-side scripts, you can then load the jQuery module via require.js as follows:
>```
>require(['jquery'], function ($) {
>    $('.someClass').addClass('someotherclass');
>});
>```

This is while [requirejs has been deprecated by NodeBB 2.0](https://nodebb.org/blog/migration-guide-for-v2/#:~:text=Require.js%20dependency%20removed)...

**Comment by barisusakli** [comment]
The require(['modulename']) syntax still works in webpack

https://github.com/NodeBB/docs/commit/cd53d3f097e59a9db44929771a0e4dd02b697ea2

**Comment by ShlomoCode** [comment]
@barisusakli 
<img width="555" alt="CleanShot 2023-02-14 at 00 26 10@2x" src="https://user-images.githubusercontent.com/78599753/218588595-1042712e-0645-482f-87d5-d709075728d1.png">

**Comment by pitaj** [comment]
It doesn't work in the browser, but it does work when the scripts are added to your plugin.json and processed by or build system
