### ISSUE TITLE
How to help Docs i18n?

### ISSUE THREAD

**Issue by a632079** [NodeBB/docs#7]
I find NodeBB Docs  use Mkdocs instead of  `readthedocs` now . But I can't find where to translate this docs.

--------------
Is it possible to add a localized third-party document link to an official document? I have created a Chinese Documents(Is not a complete official document translation) via kancloud.cn

**Comment by julianlam** [comment]
Hi there, we've made the decision to stick to English documentation for now as it was becoming hard to keep various localisations in sync with changes made in the English language docs.

Chinese documentation should definitely exist, although it may be a community effort for now. Hope that is okay :frowning:
